In [2]:
import numpy as np

scores = [4.8, 3.5, 4.1]
# ascending is default:
print(np.argsort(scores))

# descending:
print(np.argsort(scores)[::-1])

np.set_printoptions(precision=4, suppress=True)
arr = np.array([13434343.34344343, 2434343.4343, 34343.434, 44343.43434343, 534343434.3434343])
print(arr)


[1 2 0]
[0 2 1]
[1.3434e+07 2.4343e+06 3.4343e+04 4.4343e+04 5.3434e+08]
